### ISSUE TITLE
gentoo patches no longer work for kernel>3.15

### ISSUE THREAD

**Issue by Yamakuzure** [init6/init_6#138]
Hi all,

the gentoo patchset can not be fetched any more via svn.
I took a brief look into /usr/portage/eclass/gentoo.eclass, and it seems that the handling has changed a lot. As far as I can see, a tarball must be downloaded from a gentoo mirror.

I see whether I can come up with a patch for the init6/eclass/gentoo.eclass, but I'll need a while to figure out what is needed and what's not.

(btw.: The current eclass can't work either, because it tries to use git to clone a subversion repo. That would need git-svn, right?)

**Comment by init6** [comment]
Now all gentoo svn mv to git ;) Info from planet.gentoo.org so need fix eclass if there is gentoo patches.

**Comment by init6** [comment]
> The current eclass can't work either, because it tries to use git to clone a subversion repo. That would need git-svn, right?

No. GENTOO_SRC from eclass! Now use svn://

**Comment by init6** [comment]
@Yamakuzure 

By default

[: ${GENTOO_SRC:=${GENTOO_SRC:-"svn://anonsvn.gentoo.org/linux-patches/genpatches-2.6/trunk"}} # Patchset sources url](https://github.com/init6/init_6/blob/master/eclass/gentoo.eclass#L44)

**Comment by Yamakuzure** [comment]
@init6 : Which default? GENTOO_SRC can neither be found as "portageq envvar" nor is it listed in any portage eclass.

See:
```bash
 ~ # USE="gentoo" ebuild /var/lib/layman/init6/sys-kernel/geek-sources/geek-sources-3.19.5.ebuild unpack
 * patch-3.19.5.xz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                        [ ok ]
 * linux-3.19.tar.xz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                      [ ok ]
 * tuxonice-for-linux-head-3.19.0-2015-02-10.patch.bz2 SHA256 SHA512 WHIRLPOOL size ;-) ...                                                    [ ok ]
 * uksm-0.1.2.3-for-v3.18.patch SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                           [ ok ]
>>> Unpacking source...
(...)
 * Extract the sources ...                                                                                                                     [ ok ]
 * Skipping update to latest upstream ...
 * Unpack - uksm
 * Unpack - ice
 * Unpack - squeue
 * Unpack - zen
cp: ‘zen-kernel-3.19.5-20150429.patch’ and ‘/home/portage/sys-kernel/geek-sources-3.19.5/temp/zen/zen-kernel-3.19.5-20150429.patch’ are the same file
 * Unpack - gentoo
/home/portage/sys-kernel/geek-sources-3.19.5/temp/environment: line 1335: cd: /home/distfiles/geek/gentoo/master: No such file or directory
fatal: Not a git repository (or any parent up to mount point /home/portage)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/home/portage/sys-kernel/geek-sources-3.19.5/temp/environment: line 1344: cd: /home/portage/sys-kernel/geek-sources-3.19.5/temp/gentoo28390/3.19: No such file or directory
 * ERROR: sys-kernel/geek-sources-3.19.5::init6 failed (unpack phase):
 *   cd /home/portage/sys-kernel/geek-sources-3.19.5/temp/gentoo28390/3.19 failed
```

Relevant output with ECLASS_DEBUG_OUTPUT="on" (after I created the missing directory by hand) :
```bash
 * Unpack - gentoo
debug: gentoo_src_unpack: entering function, parameters: 
fatal: Not a git repository (or any parent up to mount point /home/distfiles)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
debug: utils_copy: entering function, parameters: /home/distfiles/geek/gentoo /home/portage/sys-kernel/geek-sources-3.19.5/temp/gentoo1102
/home/portage/sys-kernel/geek-sources-3.19.5/temp/environment: line 1345: cd: /home/portage/sys-kernel/geek-sources-3.19.5/temp/gentoo1102/3.19: No such file or directory
 * ERROR: sys-kernel/geek-sources-3.19.5::init6 failed (unpack phase):
 *   cd /home/portage/sys-kernel/geek-sources-3.19.5/temp/gentoo1102/3.19 failed
 * 
 * Call stack:
 *     ebuild.sh, line   93:  Called src_unpack
 *   environment, line 1920:  Called geek-sources_src_unpack
 *   environment, line 1248:  Called gentoo_src_unpack
 *   environment, line 1345:  Called die
 * The specific snippet of code:
 *       cd "${CTD}"/${KMV} || die "${RED}cd ${CTD}/${KMV} failed${NORMAL}";
```

This just doesn't fit together somehow. :-(

**Comment by init6** [comment]
@Yamakuzure

In gentoo.eclass GENTOO_SRC by default defined as

[: ${GENTOO_SRC:=${GENTOO_SRC:-"svn://anonsvn.gentoo.org/linux-patches/genpatches-2.6/trunk"}} # Patchset sources url](https://github.com/init6/init_6/blob/master/eclass/gentoo.eclass#L44)

To test current eclass run

> svn co svn://anonsvn.gentoo.org/linux-patches/genpatches-2.6/trunk

**Comment by Yamakuzure** [comment]
First of all, thank you for your patience!

I have tried it out, and it times out.

```bash
 ~/tmp $ LC_ALL=C svn co svn://anonsvn.gentoo.org/linux-patches/genpatches-2.6/trunk
svn: E000110: Unable to connect to a repository at URL 'svn://anonsvn.gentoo.org/linux-patches/genpatches-2.6/trunk'
svn: E000110: Can't connect to host 'anonsvn.gentoo.org': Connection timed out
```

So, how do we fix gentoo.eclass? Does anybody have an idea?

**Comment by init6** [comment]
From [genpatches homepage](https://dev.gentoo.org/~mpagano/genpatches/) :

> * [Trunk](https://dev.gentoo.org/~mpagano/genpatches/trunk/)
>
>  Latest split-out patches from our current development trees, viewable on the web.
>
> * [Repositor](http://git.overlays.gentoo.org/gitweb/?p=proj/linux-patches.git;a=summary)
>
>  The entire repository and its history is browseable here.

**Comment by Yamakuzure** [comment]
init6, do you even try these out?

1. The Anonymous access is what does no longer work and times out, see above.
2. The "Trunk" is https://dev.gentoo.org/~mpagano/genpatches/trunk/, which is the source for the tarballs I posted the address to. Why fetch a bunch of patches when they can be downloaded neatly packed?
3. And the Repository is https://overlays.gentoo.org/gitweb/?p=proj/linux-patches.git;a=summary which results in: 404 NOT FOUND

So it looks like the tarballs to be the only viable way left.

OH! WAIT!

According to this news item here:
https://www.gentoo.org/news/2015/04/25/anongit-overlays.html
the URL changed.

And this works:
```bash
git clone git://anongit.gentoo.org/proj/linux-patches
```

The patches for 3.19.5 (as it is the example I used above) can be seen using the tag "3.19-5".

The quickest way is:
```bash
git clone --branch 3.19-5 --depth=1 git://anongit.gentoo.org/proj/linux-patches
```

So we *can* fix this without needing tarballs after all! *yay*

**Comment by Yamakuzure** [comment]
gentoo.eclass fixed, pull request created. ;-)

Again, thank you for your patience, although it took us a while. Hell, we sorted it out, didn't we?
