### ISSUE TITLE
Mistaken kernel version in some patch

### ISSUE THREAD

**Issue by jorgicio** [init6/init_6#151]
Hi!

In one of the patches, leaves Makefile with Kernel 4.0.0, being installed the 4.0.2. Please, check and fix that, because it believes I'm compiling 4.0.0 and not 4.0.2.

Thanks :)

**Comment by init6** [comment]
USE flags? Some log files?

**Comment by jorgicio** [comment]
USE="bfq bfs ck gentoo pf symlink uksm"
And I didn't have some log files. BTW, I had do edit by hand the Makefile in the kernel sources, in the line SUBLEVEL. By default, it was 0.

**Comment by init6** [comment]
[USE="lqx openvz pf rh uek zen"](https://github.com/init6/init_6/blob/master/eclass/geek-sources.eclass#L113)
 on any **4.x.x** always need only 4.0.0 the same as on any **3.x.x** need only 3.0.0.

These patches **USE="lqx openvz pf rh uek zen"** by themselves contain updates to **3.x.x/4.x.x**

That's not a bug. And not our bug.
